### ISSUE TITLE
Fehler beim Kompilieren

### ISSUE THREAD

**Issue by Iceskull7** [NorthyIE/DasKit-C7BB-Tuning#1]
Hallo ich habe mir einen ESP32, Julet Kabel und Daumengas gekauft.

Ich habe leider gar keine Ahnung von dem ESP32...

Den code habe ich in das Arduino IDE kopiert und auf Hochladen gedrückt.

hier kommt dann eine Fehlermeldung:

Serial1 was not declared in this scope

`Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Daniel\Documents\Arduino\sketch_apr11a\sketch_apr11a.ino: In function 'void setup()':

sketch_apr11a:19:5: error: 'Serial1' was not declared in this scope

     Serial1.begin(BAUD_RATE,SERIAL_8N1,12,13);                    //Software seriell1

     ^

sketch_apr11a:20:5: error: 'Serial2' was not declared in this scope

     Serial2.begin(BAUD_RATE,SERIAL_8N1,14,15);

     ^

C:\Users\Daniel\Documents\Arduino\sketch_apr11a\sketch_apr11a.ino: In function 'void recvBytesWithStartEndMarkers1()':

sketch_apr11a:44:12: error: 'Serial1' was not declared in this scope

     while (Serial1.available() > 0 && newData1 == false) {

            ^

C:\Users\Daniel\Documents\Arduino\sketch_apr11a\sketch_apr11a.ino: In function 'void recvBytesWithStartEndMarkers2()':

sketch_apr11a:83:12: error: 'Serial2' was not declared in this scope

     while (Serial2.available() > 0 && newData2 == false) {

            ^

C:\Users\Daniel\Documents\Arduino\sketch_apr11a\sketch_apr11a.ino: In function 'void showNewData()':

sketch_apr11a:155:9: error: 'Serial1' was not declared in this scope

         Serial1.write(sendBytes,12);              // Telegramm rausschicken

         ^

exit status 1
'Serial1' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`

Muss ich an den Einstullungen an der Arduino IDE was machen?

Gruß 
Daniel

**Comment by NorthyIE** [comment]
Hallo Daniel,

du musst die Arduino-IDE noch auf den ESP32 umstellen. Aktuell hast du anscheinend Board: "Arduino/Genuino Uno" ausgewählt.

Installiere einfach die ESP32-Boards über den Paketmanager (Anleitung: https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md) und wähle dann dein ESP-Board aus.

Ich habe einen FireBeetle-Clon, wie im Anhang, da kompiliert das ganze ohne Probleme!

Gruß
Sebastian
![Capture](https://user-images.githubusercontent.com/36325097/55987417-ccfaf680-5ca1-11e9-9ef7-2f41af59384d.PNG)

**Comment by Iceskull7** [comment]
Ohh ja hat geklappt, danke!
