### ISSUE TITLE
Kommunikation mit Display Fehlerhaft

### ISSUE THREAD

**Issue by Iceskull7** [NorthyIE/DasKit-C7BB-Tuning#2]
Hallo Sebastian,

ich hoffe du bist noch an dem Projekt dran :)

Ich habe alles soweit zusammengebaut und getestet.
Es scheint auch mit gewissen Problemen zu funktionieren, selbst Daumengas geht.

Einziges Problem, ist die Kommunikation mit dem Display.

- Es werden keine KM, KM/H übertragen.
- Die Akku Anzeige spinnt und springt wild von voll auf leer hin und her.
- Es ist nur möglich zwischen den 6 Modi einzustellen

Ist es bei dir auch so, o.ä? bzw gar nicht gewollt, am Display die richtige Anzeige zu haben?

Desweiteren schaltet sich das Display irgendwann ab, schätze mal aufgrund der hin und her springenden Akku Anzeige. Wenn das Display denkt der Akku ist leer.

Hoffe du kannst hier Licht ins Dunkle bringen.

Hier das verwendete Verkabelungsschema aus dem Forum:
![grafik](https://user-images.githubusercontent.com/25932522/56139458-36784f00-5f99-11e9-894c-7ba30c4b923f.png)
Evtl liegt hier ja der Fehler? Sind es die Selben Pins wie im Code?
Im Code habe ich Pin 15 gesehen, der wird hier gar nicht verkabelt.

Genutz wurde dein Original-ESP32 Code

Beste Grüße
Daniel

**Comment by NorthyIE** [comment]
Hallo Daniel,
entschuldige die späte Antwort, ich war nicht im Lande :)

Bei mir funktioniert die Kommunikation zwischen Display, ESP und Controller einwandfrei. Auch die KM/h-Anzeige aktualisiert einwandfrei.
Die KM/H werden direkt (unbearbeitet) vom Controller ans Display geschickt. Wenn die Anzeige bei dir gar nicht stattfindet, scheint es hier ein generelles Problem zu geben. Auch die Akkuanzeige wird (soweit mir bekannt) direkt vom LCD bearbeitet.

Das Bild aus dem Forum ist noch der ältere Arduino, kannst du mir ein Bild schicken, welche Pins du auf dem ESP32 genau verwendet hast?
Es werden GPIO 12,13 (Serial1) und 14,15 (Serial2) verwendet. Da aber über Serial2 nur Daten in eine Richtung gehen, ist GPIO 15 nicht verbunden.

Entweder ist es tatsächlich ein Pin-Problem, sonst würde ich auf einen Wackelkontakt bzw. ein Lötstellenproblem tippen.

Gruß
Sebastian

**Comment by NorthyIE** [comment]
@Iceskull7 
Hallo Daniel,

hast Du das Problem inzwischen beheben können?

**Comment by Iceskull7** [comment]
Ohh sorry, danke für die Antwort!
Ich habe mir einen ES8266 gekauft und den original Code genommen.

Das hat mein Problem gelöst, hat alles funktioniert.

Aber schau mal hier ab Seite 10: https://pedelec-ebike-forum.de/Thread-Kommunikation-zwischen-C7-Display-und-Venice?page=10


Ich kann dir nicht sagen wo das Problem beim ESP 32 liegt, wenn es bei dir geht ist der Code wohl richtig.

**Comment by NorthyIE** [comment]
@Iceskull7 
Hallo Daniel,

danke für die Rückmeldung.
Hmm, komisch, ich habe mit meinem ESP32 keine Probleme.

Hättest Du eventuell die Möglichkeit, mir deinen ESP32 zu Testzwecken zuzuschicken? Ich würde mir dies gerne genauer anschauen, bzw. verstehe ich nicht, wieso es bei dir zu diesen Problemen kommt. Wenn es mit dem 8266 funktioniert ist es ja dann kein Wackelkontakt oder ähnliches. Vielleicht liegt es an deiner Version des ESPs. Wäre sehr hilfreich, damit andere nicht in eine ähnliche Situation kommen. Ich schicke ihn dir auch gerne wieder zurück :)

Danke auch für den Link, ich werde mich dort mehr in die Thematik einlesen. Bitte auch gerne den anderen Forums-teilnehmen bescheid geben, dass meine Kopie des Codes Open Source ist (selber habe ich ja nicht viel im Original-Code geändert, nur erweitert und für den ESP32 angepasst).  Ich bin für Veränderungen/Anpassungen/Verbesserungen dankbar :)

Gruß
Sebastian

**Comment by NorthyIE** [comment]
@Iceskull7 
Hallo Daniel,
ich schließe erstmal das Ticket, da dieses Problem mit meinem ESP nicht reproduzierbar ist.
Falls Du mir den ESP für Testzwecke zukommen lassen möchtest, kannst du mich gerne direkt kontaktieren.

Gruß
Sebastian

**Comment by Iceskull7** [comment]
Hi Sebastian,

sorry für die späte Rückmeldung, denke es würde sich kaum Lohnen es hin und her zuschicken.
Wegen den geringen kosten auf Amazon  (ESP32 NodeMCU Module WLAN WiFi Development Board mit CP2102)

Ich habe jedoch zurzeit nichts am Rad verbaut, ich hatte mal einen Totalausfall auf dem Heimweg.
Der Akku ging nicht mehr an, erst nach anschließen ans Netzteil war er wieder da (zu 95% voll)

Aber ich danke dir trotzdem für die Hilfe!

Beste Grüße
Daniel
