### ISSUE TITLE
How to Connect

### ISSUE THREAD

**Issue by jeromeatneotek** [NorthyIE/DasKit-C7BB-Tuning#4]
Thank you so much for providing this solution. I have a friend I am trying to assist and am unsure how to connect the ESP32. Can you confirm how you wire this up please?

**Comment by NorthyIE** [comment]
Sorry for the "slight" delay in getting back to you :)
Here is a diagram for the wiring: https://www.pedelecforum.de/forum/index.php?attachments/schema-png.219063/

It was taken from this thread: https://www.pedelecforum.de/forum/index.php?threads/kommunikation-zwischen-c7-display-und-motorkontroller-ncm-venice-das-kit.57050/
